### ISSUE TITLE
Debug water_potential_hydrogen firmware issue. Causing lose sync to arduino and raspberrypi (2d)

### ISSUE THREAD

**Issue by gordonbrander** [OpenAgInitiative/openag_brain#199]
(Exported from Trello https://trello.com/c/99HgSuYq/999-debug-water-potential-hydrogen-firmware-issue-causing-lose-sync-to-arduino-and-raspberrypi-2d)

**Comment by Spaghet** [comment]
Is this just the sensor being in UART mode? Or something more software side

**Comment by rwdavis513** [comment]
I ran into the same issue with the nutrient pumps today. I need to verify but I'm guessing it is because the bottles were empty and therefore werent able to pump correctly. I suspect the pumps throw some kind of error if they arent able to pump. Need to investigate and see what happens when no bottle is attached.

**Comment by Spaghet** [comment]
There's no such error case, it's probably just because the pump firmware is written incorrectly.
There are blocking calls to `delay()` in the doser pump and pulse actuator firmware code which has been fixed in the bespoke_serial firmware.
